version: 2.1

executors:
  rails:
    docker:
      - image: cimg/ruby:3.1.2-browsers
        environment:
          RAILS_ENV: test
          RACK_ENV: test
          RAILS_TEST_PORT: 5002
          PAGER: cat # stops psql db:schema:load hanging
      - image: circleci/redis:alpine
      - image: circleci/postgres:12.2-ram
        environment:
          POSTGRES_DB: circle_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
    working_directory: /home/circleci/web-app

commands:
  bundle-install:
    steps:
      - run:
          name: Set bundle path
          command: bundle config --local path vendor/bundle
      - run:
          name: Bundle install
          command: bundle install --jobs=4 --retry=3

  database-setup:
    description: Prepare database
    steps:
      - run:
          name: Waiting for database
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Installing postgresql-client
          command: sudo apt update && sudo apt install postgresql-client-12
      - run:
          name: Load schema
          command: bin/rails db:schema:load

  build-web-app:
    description: Building web-app
    steps:
      - checkout
      - run:
          name: Create date_dependency_checksum
          command: date '+%Y %U' > date_dependency_checksum
      - run:
          name: Copy configs into place
          command: |
            cp config/{database_circleci,database}.yml
      - bundle-install
      - database-setup

jobs:
  rspec:
    executor: rails
    steps:
      - build-web-app
      - run:
          name: RSpec
          command: bundle exec rspec

  seeds-development:
    executor: rails
    steps:
      - build-web-app
      - run:
          name: Development seeds
          command: FIXTURE_PATH=db/fixtures/development bin/rails db:seed

workflows:
  version: 2
  build_and_test:
    jobs:
      - rspec
      - seeds-development
